-- Create table for Drugs
CREATE TABLE IF NOT EXISTS drugs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    brand_name TEXT NOT NULL,
    generic_name TEXT,
    ndc TEXT,
    dosage TEXT,
    exp_date TEXT,
    sup_id INTEGER,
    purchase_price DECIMAL,
    sell_price DECIMAL
);

-- Create table for Inventory
CREATE TABLE IF NOT EXISTS inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    med_name TEXT REFERENCES drugs(brand_name),
    batch_id TEXT,
    quantity INTEGER,
    expiry_date DATE,
    status TEXT
);

-- Create table for Prescriptions (optional, for future use)
CREATE TABLE IF NOT EXISTS prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    patient_id INTEGER,
    phys_id INTEGER,
    ndc TEXT,
    qty INTEGER,
    days INTEGER,
    refills INTEGER,
    status TEXT
);

-- Enable Row Level Security (RLS) but allow public access for this demo
-- In production, you would lock this down.
ALTER TABLE drugs ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE prescriptions ENABLE ROW LEVEL SECURITY;

-- Policy to allow generic read/write access for the Anon key (for demo simplicity)
CREATE POLICY "Allow Anon Access Drugs" ON drugs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Anon Access Inventory" ON inventory FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow Anon Access Prescriptions" ON prescriptions FOR ALL USING (true) WITH CHECK (true);
